BEGIN;

SET ROLE jr_leads_owner;

ALTER TYPE lead_type
ADD VALUE IF NOT EXISTS 'nyife';

ALTER TABLE leads
  ADD COLUMN IF NOT EXISTS company VARCHAR(500) NULL,
  ADD COLUMN IF NOT EXISTS plan VARCHAR(200) NULL,
  ADD COLUMN IF NOT EXISTS demo_date VARCHAR(50) NULL,
  ADD COLUMN IF NOT EXISTS demo_time VARCHAR(50) NULL,
  ADD COLUMN IF NOT EXISTS utm_term VARCHAR(500) NULL,
  ADD COLUMN IF NOT EXISTS utm_content VARCHAR(500) NULL,
  ADD COLUMN IF NOT EXISTS fbclid VARCHAR(1000) NULL,
  ADD COLUMN IF NOT EXISTS gclid VARCHAR(1000) NULL;

RESET ROLE;

COMMIT;
